[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
escrow = "5MaJShYoCFPtoghs5pTyVHa44w4BBvxCTJsZCjnCe3y1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run jest --preset ts-jest"
